2025-04-01 19:33:02,374 - INFO - 
Config:
'add_train': False
'batch_size': 64
'cur_time': '25-04-01_19-33-02'
'do_figure_save': True
'do_log_print_to_screen': True
'do_log_save_to_file': True
'do_predict': True
'do_train': True
'do_train_visualized': False
'dropout_rate': 0.2
'epoch': 20
'feature_path': 'data/features/BTCUSD_1h_Binance.csv'
'features': ['Close'
'Open'
'High'
'Low'
'Volume']
'figure_save_path': './figure/'
'hidden_size': 128
'input_size': 5
'label_path': 'data/labels/BTCUSD_1h_Binance.csv'
'learning_rate': 0.001
'log_save_filename': 'BTCUSD_1h_Binance.log'
'log_save_path': './log/25-04-01_19-33-02_/'
'lookback': 48
'model_name': 'model.pth'
'model_save_path': './checkpoint/'
'num_layers': 2
'patience': 5
'random_seed': 42
'seq_len': 48
'shuffle_train_data': True
'train_data_path': 'data/raw/BTCUSD_1h_Binance.csv'
'train_data_rate': 0.85
'use_cuda': False
'valid_data_rate': 0.15
2025-04-01 19:33:02,397 - ERROR - Run Error
Traceback (most recent call last):
  File "/Users/yejoonjung/Documents/Projects/trading-signal-classifier/train_and_test.py", line 71, in main
    train(config, logger, [train_X, train_Y, valid_X, valid_Y])
  File "/Users/yejoonjung/Documents/Projects/trading-signal-classifier/model/lstm.py", line 44, in train
    train_loader = DataLoader(TensorDataset(train_X, train_Y), batch_size=config.batch_size)    # DataLoader automatically generates trainable batch data
  File "/Users/yejoonjung/anaconda3/envs/timemoe/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 205, in __init__
    assert all(
AssertionError: Size mismatch between tensors
